### ISSUE TITLE
For Bluetooth, can I still use the same rtk_hciattach from Android-x86 ?

### ISSUE THREAD

**Issue by hmtheboy154** [youling257/rockchip_wlan#2]
Alternatively I have this which based on newer bluez tools (5.54), can you help me check if this is usable with the driver ?

https://github.com/supremegamers/hcitools/tree/12l-x86

**Comment by youling257** [comment]
needn't start rtk_hciattach and btattach since many years ago.

you can remove these init.sh and init.x86.rc,
https://github.com/supremegamers/device_generic_common/blob/bliss/11-x86/init.sh#L125
https://github.com/supremegamers/device_generic_common/blob/bliss/11-x86/init.sh#L142
https://github.com/supremegamers/device_generic_common/blob/bliss/11-x86/init.x86.rc#L116
https://github.com/supremegamers/device_generic_common/blob/bliss/11-x86/init.x86.rc#L126

Huy Minh ***@***.***> 于 2023年6月20日周二 下午6:23写道：

**Comment by hmtheboy154** [comment]
Thanks
